# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'DatePickerTimePickerDialog' do

  # Pods for DatePickerTimePickerDialog
  config = use_native_modules!
  use_react_native!(
    :path => config["reactNativePath"],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  target 'DatePickerTimePickerDialogTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
